#ifndef MESSAGEDEFINE_H_
#define MESSAGEDEFINE_H_
#include "stdafx.h"
#ifdef __x86_64__
typedef uint64_t SOCKET;
#else
typedef uint32_t SOCKET;
#endif

typedef enum CASTMSGTYPE
{
	CASTMSGTYPE_GETIDENTIFYIP = 0,
	CASTMSGTYPE_GETIDENTIFYIP_ACK
	
}CASTMSGTYPE;

typedef enum MESSAGETYPE
{
    MESSAGETYPE_CMD = 1000
}MESSAGETYPE;

typedef enum MESSAGETYPECMD
{
    MESSAGETYPECMD_CHECKFILE = 1000, //通过拍摄时间拍摄手机判断是否在同一个手机同一个时间有拍摄 有就认为是同一个文件
    MESSAGETYPECMD_CHECKFILE_ACK,
    MESSAGETYPECMD_CHECKMD5,
    MESSAGETYPECMD_CHECKMD5_ACK, //如果可以传输(MD5值不重复),给出缩略图IP地址端口号
    MESSAGETYPECMD_UPLOADFILE,//发送文件请求
    MESSAGETYPECMD_UPLOADFILE_ACK, //发送文件请求响应,成功给出IP地址和端口号
    MESSAGETYPECMD_REPORTINFO,  //传递给他小图的名称 大图(视频的名称) 位置 拍摄时间 类型(图片/视频) MD5值 文件大小 设备类型
    MESSAGETYPECMD_REPORTINFO_ACK,
	MESSAGETYPECMD_DEVICEINFO, //获取设备信息
	MESSAGETYPECMD_DEVICEINFO_ACK,  //获取设备信息的响应
	MESSAGETYPECMD_DISKINFO, //获取磁盘信息
    MESSAGETYPECMD_DISKINFO_ACK,  //获取磁盘信息的响应
	MESSAGETYPECMD_LOGIN, //登录
    MESSAGETYPECMD_LOGIN_ACK,  //登录的响应
	MESSAGETYPECMD_PWDTIP, //获取密码提示信息
    MESSAGETYPECMD_PWDTIP_ACK,  //获取密码提示信息的响应
	MESSAGETYPECMD_RESETUSER, //重置用户信息
    MESSAGETYPECMD_RESETUSER_ACK,  //重置用户信息的响应
	MESSAGETYPECMD_UPDATEDEVICEINFO, //更新设备名称
    MESSAGETYPECMD_UPDATEDEVICEINFO_ACK,  //更新设备名称的响应
	MESSAGETYPECMD_SERVERITEMS, //服务器上的媒体分页查询
    MESSAGETYPECMD_SERVERITEMS_ACK,  //服务器上的媒体分页查询响应
	MESSAGETYPECMD_MEDIAITEMINFO, //每个媒体的详细信息
    MESSAGETYPECMD_MEDIAITEMINFO_ACK,  //每个媒体的详细信息响应
	MESSAGETYPECMD_MEDIAITEMDEL, //删除媒体信息
    MESSAGETYPECMD_MEDIAITEMDEL_ACK,  //删除媒体信息响应
	MESSAGETYPECMD_MEDIAITEMFAVORITE, //媒体添加喜欢
    MESSAGETYPECMD_MEDIAITEMFAVORITE_ACK,  //媒体添加喜欢响应
	MESSAGETYPECMD_MEDIAYEARLIST,  //照片年份列表
	MESSAGETYPECMD_MEDIAYEARLIST_ACK,  //照片年份列表响应
	MESSAGETYPECMD_MEDIAYEARINFO,  //照片年份视频和图片的数量
	MESSAGETYPECMD_MEDIAYEARINFO_ACK,  //照片年份视频和图片的数量响应
	MESSAGETYPECMD_MEDIADEVNAMES,  //上传的所有设备名称
	MESSAGETYPECMD_MEDIADEVNAMES_ACK,  //上传的所有设备名称响应
	MESSAGETYPECMD_MEDIARECENTINFO,  //最近上传的数据计数
	MESSAGETYPECMD_MEDIARECENTINFO_ACK,  //最近上传的数据计数响应
	MESSAGETYPECMD_MEDIAFAVORITEINFO,  //最近上传的喜欢计数
	MESSAGETYPECMD_MEDIAFAVORITEINFO_ACK,  //最近上传的喜欢计数响应
	MESSAGETYPECMD_MEDIAUNCHECKGPS,  //有gps但是没有获取位置,获取到以后依次赋值位置
	MESSAGETYPECMD_MEDIAUNCHECKGPS_ACK,  //有gps但是没有获取位置响应
	MESSAGETYPECMD_MEDIANUPDATEGPSWEIZHI,  //通过GPS更新位置
	MESSAGETYPECMD_MEDIANUPDATEGPSWEIZHI_ACK,  //通过GPS更新位置响应
	MESSAGETYPECMD_YEARLOCATIONGROUP,  //一年内的相片按照gps位置分组
	MESSAGETYPECMD_YEARLOCATIONGROUP_ACK,  //一年内的相片按照gps位置分组响应
	MESSAGETYPECMD_YEARLOCATIONGROUPTONGJI,  //每年的照片和视频分组统计
	MESSAGETYPECMD_YEARLOCATIONGROUPTONGJI_ACK,  //每年的照片和视频分组统计响应
	MESSAGETYPECMD_UPDATEPAISHETIME,  //修改照片的拍摄时间
	MESSAGETYPECMD_UPDATEPAISHETIME_ACK,  //修改照片的拍摄时间响应
	MESSAGETYPECMD_UPDATEGPSADDR,  //修改照片的GPS
    MESSAGETYPECMD_UPDATEGPSADDR_ACK,  //修改照片的GPS响应
	MESSAGETYPECMD_ABOUTDEVICE,  //关于设备
	MESSAGETYPECMD_ABOUTDEVICE_ACK,  //关于设备
	MESSAGETYPECMD_UPDATEDEVICETIME,  //更新设备时间
	MESSAGETYPECMD_UPDATEDEVICETIME_ACK,  //更新设备响应
	MESSAGETYPECMD_GETBRTYPE,  //获取br类型
	MESSAGETYPECMD_GETBRTYPE_ACK,  //获取br类型响应
	MESSAGETYPECMD_SETBRTYPE,  //设置br类型
	MESSAGETYPECMD_SETBRTYPE_ACK,//设置br类型响应
	MESSAGETYPECMD_GETWIFIITEMS, //获取附近的无线设备
	MESSAGETYPECMD_GETWIFIITEMS_ACK, //获取附近的无线设备响应
	MESSAGETYPECMD_GETSTOREWIFIITEMS, //获取存储的无线设备
	MESSAGETYPECMD_GETSTOREWIFIITEMS_ACK, //获取存储的无线设备响应
	MESSAGETYPECMD_GETHOTPOT,//获取热点信息
	MESSAGETYPECMD_GETHOTPOT_ACK,//获取热点信息响应
	MESSAGETYPECMD_SETHOTPOT,//设置热点信息
	MESSAGETYPECMD_SETHOTPOT_ACK,//设置热点信息响应
	MESSAGETYPECMD_CONNECTWIFIITEM, //连接wifi设备
	MESSAGETYPECMD_CONNECTWIFIITEM_ACK,//连接wifi设备响应
	MESSAGETYPECMD_UNCONNECTWIFIITEM, //断开wifi设备连接
	MESSAGETYPECMD_UNCONNECTWIFIITEM_ACK,//断开wifi设备连接响应
	MESSAGETYPECMD_GETWIFISTATUS, //获取WLAN1状态
	MESSAGETYPECMD_GETWIFISTATUS_ACK,//获取WLAN1状态响应
	MESSAGETYPECMD_DELSTOREWIFIITEM, //删除WLAN1口的配置项
	MESSAGETYPECMD_DELSTOREWIFIITEM_ACK,//删除WLAN1口的配置项响应
	MESSAGETYPECMD_SETCOVER, //设置封面
	MESSAGETYPECMD_SETCOVER_ACK,//设置封面响应
	MESSAGETYPECMD_MEDIAMONTHLIST,  //照片月份列表
	MESSAGETYPECMD_MEDIAMONTHLIST_ACK,  //照片月份列表响应
	MESSAGETYPECMD_MEDIADAYSLIST,  //照片日列表
	MESSAGETYPECMD_MEDIADAYSLIST_ACK,  //照片日列表响应
	MESSAGETYPECMD_MEDIAYEARMONTHDAYCOVER,  //照片日头像
	MESSAGETYPECMD_MEDIAYEARMONTHDAYCOVER_ACK,  //照片日头像响应
	MESSAGETYPECMD_MEDIACLEARCACHESTART,  //开始清理缓存
	MESSAGETYPECMD_MEDIACLEARCACHESTART_ACK,  //开始清理缓存响应
	MESSAGETYPECMD_MEDIACLEARCACHEPROCESS,  //清理缓存进度
	MESSAGETYPECMD_MEDIACLEARCACHEPROCESS_ACK,  //清理缓存进度响应
	MESSAGETYPECMD_GROUPINFO, //分类信息查询
	MESSAGETYPECMD_GROUPINFO_ACK, //分类信息查询响应
	MESSAGETYPECMD_GROUPADD, //添加分类信息
	MESSAGETYPECMD_GROUPADD_ACK, //添加分类信息响应
	MESSAGETYPECMD_GROUPUPDATE, //更新分类信息
	MESSAGETYPECMD_GROUPUPDATE_ACK, //更新分类信息响应
	MESSAGETYPECMD_GROUPDEL, //删除分类信息
	MESSAGETYPECMD_GROUPDEL_ACK, //删除分类信息响应
	MESSAGETYPECMD_GROUPITEMDETAIL,//获取分组项详情
	MESSAGETYPECMD_GROUPITEMDETAIL_ACK,//获取分组项详情响应
	MESSAGETYPECMD_GROUPNAMESFROMITEMID,//获取图片视频的分组信息
	MESSAGETYPECMD_GROUPNAMESFROMITEMID_ACK,//获取图片视频的分组信息响应
	MESSAGETYPECMD_MEDIAITEMGROUPSETTING,//媒体信息设置
	MESSAGETYPECMD_MEDIAITEMGROUPSETTING_ACK,//媒体信息设置响应
	MESSAGETYPECMD_GROUPNAMEFROMID,//通过ID获取分组名称
	MESSAGETYPECMD_GROUPNAMEFROMID_ACK,//通过ID获取分组名称响应
	MESSAGETYPECMD_MEDIAITEMSGROUPADD,//给照片和视频批量添加分组
	MESSAGETYPECMD_MEDIAITEMSGROUPADD_ACK//给照片和视频批量添加分组响应
}MESSAGETYPECMD;
#pragma pack (1)
typedef struct InnerBase
{
	uint16_t iMsgType;//消息类型
	uint32_t iMsgLen;//消息长度
	char szBuf[1];
}InnerBase;
typedef struct BaseMsg
{
	uint8_t iVersion;
	uint32_t iDataLen;
	SOCKET iSockfd;
    char* pExtra;
	char* pszBuf;
	struct BaseMessage* pBaseMessage;
}BaseMsg;
struct BaseMessage
{
	uint8_t iVersion;
	uint32_t iDataLen;
	char szBuf[1];
};
#pragma pack ()
#endif
